version: "3"
services:
  wp:
    container_name: WordPress_Container
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    ports:
      - 80:80 # change ip if required
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html # Full wordpress project
      #- ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      #- ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: database_name
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: db_password
      WORDPRESS_TABLE_PREFIX: pb_
    depends_on:
      - db
    restart: always

  wpcli:
    container_name: WordPress_CLI_Container
    image: wordpress:cli
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
    depends_on:
      - db
      - wp
    restart: always

  db:
    container_name: MySql_Container
    image: mysql:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    ports:
      - ${IP}:3306:3306 # change ip if required
    command:
      [
        "--default_authentication_plugin=mysql_native_password",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: prothoma_blog
      MYSQL_ROOT_PASSWORD: root_pasword
    restart: always

  phpmyadmin:
    container_name: PhpMyAdmin_Container
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: root_pasword
      PMA_HOST: db
    image: phpmyadmin
    ports:
      - "3307:80"
    restart: always
    volumes:
      - ./wp-app:/var/www/html/phpmyadmin

volumes:
  db_data:
